Add Zoom meeting invitation to the Meeting Page
ucla/moodle-mod_zoom pull request #170
Opened 2020-12-02 18:18 UTC by jackvanb

The meeting invitation is shown when the user clicks the 'Show meeting invitation' link, and is hidden when the user clicks the 'Hide meeting invitation' link.

![show-invite-text-revised](https://user-images.githubusercontent.com/17104896/100914262-ae093380-3487-11eb-9449-66563acf1b91.gif)

2020-12-02 18:37 UTC, rlorenzo requested changes

2020-12-02 18:37 UTC, rlorenzo commented on amd/src/toggle_text.js
> +export const init = (showMoreText, showLessText) => {
@jackvanb Rather than passing in the strings as parameters, try using the core/str library. See the example at https://docs.moodle.org/dev/Javascript_Modules#.22Hello_World.22_I_am_a_Javascript_Module

import Str from 'core/str';

Then in your code you can get the string for the buttons like: 

Str.get_string('meeting_invite_show', 'mod_zoom');

2020-12-02 18:37 UTC, rlorenzo commented on view.php
> +$meetinginvite = $response->invitation;
@jackvanb Seems we will always be calling $response->invitation everytime we call get_meeting_invitation().

I see in the API documentation that it only returns one item in the object: https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetinginvitation

So to simplify things, can you make get_meeting_invitation() return $response->invitation so subsequent calls don't need to do the same thing? The get_meeting_invitation() method should just return the invitation text and not an object with the invitation as a member variable.

2020-12-02 21:50 UTC, jackvanb commented on amd/src/toggle_text.js
> +export const init = (showMoreText, showLessText) => {
Done

2020-12-02 21:50 UTC, jackvanb commented on view.php
> +$meetinginvite = $response->invitation;
Done

2020-12-02 21:52 UTC, rlorenzo commented on amd/src/toggle_text.js
> +      button.innerHTML = await getString("meeting_invite_show", "mod_zoom");
@jackvanb Wow.. each call to getString will be its own web service call? That looks to be inefficient. Can you change it back to what you had before by passing in the string as a parameter?

2020-12-02 23:15 UTC, jackvanb commented on amd/src/toggle_text.js
> +      button.innerHTML = await getString("meeting_invite_show", "mod_zoom");
@rlorenzo Looks like there's a cache, so the promise will return immediately after the first time. So this should be equivalent to doing it the other way.

https://github.com/ucla/moodle/blob/master/lib/amd/src/str.js#L33

2020-12-02 23:22 UTC, rlorenzo commented on amd/src/toggle_text.js
> +      button.innerHTML = await getString("meeting_invite_show", "mod_zoom");
@jackvanb Let's try it. Put it on TEST, but if there's a delay when clicking on the button it is better if we just pass it the strings right away

2020-12-04 20:11 UTC, jrchamp commented on styles.css
> +#show-more-button {
This doesn't say zoom in it and might apply to all "show more button"s anywhere this is installed.
```
#show-more-button {
```

2020-12-04 20:13 UTC, rlorenzo commented on styles.css
> +#show-more-button {
@jackvanb Use the existing Bootstrap spacer utility classes. See https://getbootstrap.com/docs/4.0/utilities/spacing/

I found that adding the class "pl-0" for padding-left zero removed the extra space when added to the button.

2020-12-04 20:49 UTC, jackvanb commented on styles.css
> +#show-more-button {
Switched to adding 'pl-0' to avoid using css rules.

2020-12-04 21:02 UTC, rlorenzo approved these changes
@jackvanb Looks good. Please squash and merge to development so we can review on TEST

2020-12-07 21:02 UTC, merged