Improve the UX of the activity instance settings page
ucla/moodle-mod_zoom pull request #201
Opened 2021-02-12 15:14 UTC by abias

This page improves the UX of the activity instance settings page in several aspects, see the commit message for details. After these changes, it aligns the admin settings page and the activity overview page based on these changes

-----
Please note that this patch is based on #200 (as both modify settings.php) and should be merged after this PR.

2021-02-12 21:58 UTC, jrchamp commented on mod_form.php
> +        $mform->addElement('text', 'meetingcode', '', array('maxlength' => '10'));
@abias I'm looking at the code and not the webpage, but the meetingcode field should still have the text label for accessibility.

2021-02-15 12:44 UTC, abias commented on mod_form.php
> +        $mform->addElement('text', 'meetingcode', '', array('maxlength' => '10'));
@jrchamp I was mainly looking at the webpage and had the goal to make the passcode widgets more clean and thus more understandable. But you are right, I forgot accessibility.

Due to the limitations of forms lib, I have now introduced another string label for the passcode field. I hope that this matches your expectations.

2021-02-15 12:45 UTC, abias commented
I have updated my PR and have force-pushed the branch.

2021-02-16 09:26 UTC, abias commented
I have fixed a small flaw that, after the redesign in this PR, the "Host video" and "Participants video" widgets were not disabled when webinar was enabled. This is now working again and the branch is force-pushed.

2021-02-17 09:09 UTC, abias commented
I have fixed a small flaw in the language pack which was modified by this patch. The branch is force-pushed.

2021-02-18 08:58 UTC, abias commented
I have rebased and force-pushed this branch after updates in #200

2021-02-19 19:27 UTC, rlorenzo requested changes
Reviewing the current Zoom "Schedule a Meeting" UI did they remove the "Join before host" option? Should that be removed here as well?

2021-02-19 19:27 UTC, rlorenzo commented on lang/en/zoom.php
>  $string['joinbeforehost'] = 'Join meeting before host';
@abias So this 'joinbeforehost' string is no longer used right? Why add 'joinbeforehostenable' when you can change the string for 'joinbeforehostenable'?

2021-02-19 19:27 UTC, rlorenzo commented on lang/en/zoom.php
> +$string['audio_both'] = 'Computer audio and Telephone';
@abias If you are trying to match the Zoom UI, then the options should say "Telephone", "Computer Audio", "Both"

![Screen Shot 2021-02-19 at 11 24 12 AM](https://user-images.githubusercontent.com/349765/108551583-012f9d00-72a5-11eb-958d-df0b4a5c97f9.png)

2021-02-22 09:45 UTC, abias commented on lang/en/zoom.php
> +$string['audio_both'] = 'Computer audio and Telephone';
@rlorenzo , my intention was mainly to get rid of the term "VoIP" which might not be understood by teachers.

I am aware that the Zoom interface has the terminology from your screenshot, but I am unsure if the Moodle plugin should adapt this wholeheartedly. My concern is that, Zoom on the activity overview page, where these strings are used as well, this would then say:

> Audio options: Both

and the teacher might wonder "Both _what_?"

So, what do you think, can we leave the change as it is contributed now or do you want to match the strings with Zoom completely?

2021-02-22 09:50 UTC, abias commented on lang/en/zoom.php
>  $string['joinbeforehost'] = 'Join meeting before host';
No, the string 'joinbeforehostenable' is still used on the Zoom activity overview page and the mobile view. But I wanted to have another string on the activity settings to align the terminology again with the Zoom original.

Would you support this idea?

2021-02-22 09:51 UTC, abias commented
I have rebased and force-pushed this branch after updates in #200, but didn't make any changes yet regarding the scope of this PR

2021-02-22 09:52 UTC, rlorenzo commented on lang/en/zoom.php
> +$string['audio_both'] = 'Computer audio and Telephone';
@abias I can see just the text both being confusing. Let's just keep what you have now

2021-02-22 09:53 UTC, abias commented
> Reviewing the current Zoom "Schedule a Meeting" UI did they remove the "Join before host" option? Should that be removed here as well?

No, that option is still there in my Zoom instance:

![grafik](https://user-images.githubusercontent.com/1092118/108691753-20743780-74fc-11eb-938d-3b143677bac0.png)

2021-02-22 09:53 UTC, rlorenzo commented on lang/en/zoom.php
>  $string['joinbeforehost'] = 'Join meeting before host';
@abias  Okay

2021-02-22 09:54 UTC, abias commented on lang/en/zoom.php
> +$string['audio_both'] = 'Computer audio and Telephone';
All right. Thank you.

2021-02-22 09:54 UTC, abias commented on lang/en/zoom.php
>  $string['joinbeforehost'] = 'Join meeting before host';
Thank you.

2021-02-23 18:47 UTC, abias commented
I have rebased and force-pushed this branch after #200 has been merged without doing any further changes regarding the scope of this PR.

@rlorenzo , if I didn't miss anything, this PR could then be merged now.

2021-02-23 23:46 UTC, rlorenzo approved these changes

2021-02-23 23:46 UTC, merged

2021-02-23 23:53 UTC, rlorenzo commented
@abias Looks great! Information is better organized. Thanks so much!